name: <L Mini App Android CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Set up Android SDK
        uses: Swisyn/setup-android-sdk@v1

      - name: Build debug APK
        run: ./gradlew assembleDebug

      - name: Run unit tests (opcional)
        run: ./gradlew testDebugUnitTest

      - name: Upload APK to Play Store (opcional)
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: ${{ secrets.PLAY_STORE_JSON_KEY }}
          packageName: com.example.your_app_package
          releaseFiles: app/build/outputs/apk/release/app-release.apk
          track: alpha # ou beta, production
